{% set name = "spatialpandas" %}
{% set version = "0.5.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 412bb93bb25f49b6c057e825560d14c06e71137228fa99dc007b3a191bfbabd1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - dask-core >=2025.1
    - fsspec >=2022.8
    - numba
    - pandas >=2.0
    - pyarrow >=14.0.1
    - retrying

test:
  imports:
    - spatialpandas
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/holoviz/spatialpandas
  summary: Pandas extension arrays for spatial/geometric operations
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hoxbro
    - andrewannex
    - maximlt
    - philippjfr
